#!/usr/bin/env python
from ConfigParser import ConfigParser
import requests
import sys

config = ConfigParser()
config.read('/usr/local/VDI/config')
address = config.get('server', 'address')
password = config.get('server', 'password')
x=0
startup_procedure=0 #define if kvm-snap is executed for vm startup or for other libvirt routine
y=len(sys.argv)
while (x != y):
    namearg=str(sys.argv[x])
    if (namearg=="-name"):
	vmname=str(sys.argv[x+1])
	startup_procedure=1
    x += 1
if (startup_procedure):
    responce=requests.post(address+"/backend.php", data={'pass': password, 'vm': vmname})
    snapshot=(responce.text)
    snapshot = snapshot.replace("\n", "")
    if (snapshot=="true"):
	print " -snapshot"

