#!/bin/bash

x=$1
name=$2
#y=-1
if [[ $x == "--help" || $x == "" ]]
then
    echo "vdi-mass-shutdown machine_count append_name. e.g. vdi-mass-shutdown 10 PC"
    exit
fi
for i in `seq -w 1 $x`;
do
    echo `virsh shutdown $name$i`
done