#!/bin/bash

x=$1
name=$2
path=$3
#y=-1
if [[ $x == "--help" || $x == "" ]]
then
    echo "vdi-new-machines machine_count append_name path  vdi-new-machines 10 PC /data"
    exit
fi

echo -n "Are you sure? All existing machines will be recreated with ney MAC adresses (yes/no)? "
read answer

if [ $answer != "yes" ]
then
    exit
fi



for i in `seq -w 1 $x`;
do
#    echo `qemu-img create -f qcow2 -b $initial $pt/$name$i.qcow2`
     echo `virt-clone --connect qemu:///system --original-xml /etc/vdi/template.xml --name $name$i  --file $path/$name$i.qcow2 --preserve-data --replace --force`
done