#!/bin/bash

x=$1
name=$2
initial=$3
#y=-1
if [[ $x == "--help" || $x == "" ]]
then
    echo "vdi-snapshots snaphot_count append_name initial_imge. e.g. vdi-snapshots 10 PC /var/lib/image.qcow2"
    exit
fi

for i in `seq -w 1 $x`;
do
    echo `qemu-img create -f qcow2 -b $initial /data/$name$i.qcow2`
done